# frozen_string_literal: true

require 'erb'

module Crudecumber
  StepResult     = Data.define(:keyword, :text, :status, :note)
  ScenarioResult = Data.define(:feature_name, :scenario_name, :tags, :step_results)

  class Reporter
    REPORT_FILE = 'crudecumber_results.html'

    def self.generate(results)
      new(results).write
    end

    def initialize(results)
      @results = results
    end

    def write
      File.write(REPORT_FILE, render)
      REPORT_FILE
    end

    private

    def render
      ERB.new(TEMPLATE, trim_mode: '-').result(binding)
    end

    def counts
      steps = @results.flat_map(&:step_results)
      { pass:  steps.count { |s| s.status == :pass },
        fail:  steps.count { |s| s.status == :fail },
        skip:  steps.count { |s| s.status == :skip },
        total: steps.count }
    end

    TEMPLATE = <<~'HTML'
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>Crudecumber Results</title>
        <style>
          body{font-family:sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#333}
          h1{border-bottom:2px solid #eee;padding-bottom:.5rem}
          .summary{display:flex;gap:1rem;margin:1rem 0;flex-wrap:wrap}
          .badge{padding:.3rem .8rem;border-radius:4px;font-weight:bold;font-size:.9rem}
          .pass{background:#d4edda;color:#155724}
          .fail{background:#f8d7da;color:#721c24}
          .skip{background:#fff3cd;color:#856404}
          .feature{margin-top:2rem}
          .feature h2{color:#444;border-bottom:1px solid #eee;padding-bottom:.3rem;font-size:1.1rem}
          .scenario{margin:1rem 0 1rem 1.5rem}
          .scenario h3{font-size:.95rem;margin:.5rem 0 .3rem}
          .tags{font-size:.8rem;color:#999;margin-bottom:.2rem}
          .step{padding:.1rem 0 .1rem 1.5rem;font-family:monospace;font-size:.88rem}
          .step.pass{color:#155724}
          .step.fail{color:#721c24;font-weight:bold}
          .step.skip{color:#856404}
          .note{font-style:italic;color:#666;font-size:.82rem;margin-left:3rem}
          footer{color:#aaa;font-size:.75rem;margin-top:3rem}
        </style>
      </head>
      <body>
        <h1>Crudecumber Results</h1>
        <% c = counts %>
        <div class="summary">
          <span class="badge pass">&#10003; <%= c[:pass] %> passed</span>
          <span class="badge fail">&#10007; <%= c[:fail] %> failed</span>
          <span class="badge skip">&#9900; <%= c[:skip] %> skipped</span>
          <span class="badge" style="background:#e9ecef"><%= c[:total] %> total steps</span>
        </div>
        <% @results.group_by(&:feature_name).each do |feature_name, scenarios| -%>
        <div class="feature">
          <h2>Feature: <%= ERB::Util.h(feature_name) %></h2>
          <% scenarios.each do |result| -%>
          <div class="scenario">
            <% unless result.tags.empty? -%>
            <div class="tags"><%= ERB::Util.h(result.tags.join(' ')) %></div>
            <% end -%>
            <h3>Scenario: <%= ERB::Util.h(result.scenario_name) %></h3>
            <% result.step_results.each do |step| -%>
            <div class="step <%= step.status %>"><%= ERB::Util.h("#{step.keyword} #{step.text}") %></div>
            <% if step.note -%>
            <div class="note">Note: <%= ERB::Util.h(step.note) %></div>
            <% end -%>
            <% end -%>
          </div>
          <% end -%>
        </div>
        <% end -%>
        <footer>Generated by Crudecumber at <%= Time.now.strftime('%Y-%m-%d %H:%M:%S') %></footer>
      </body>
      </html>
    HTML
  end
end
